### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: Yanjwz.

### ISSUE THREAD

**Issue by Q1ngS0ng** [zhoumingyi/ModelObfuscator#1]
Data type of this model is float32
Traceback (most recent call last):
  File "test_model.py", line 73, in <module>
    model_test(os.path.join(model_path, model_name))
  File "test_model.py", line 46, in model_test
    interpreter.allocate_tensors()
  File "/root/anaconda3/envs/code275/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 513, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: Yanjwz.

**Comment by zhoumingyi** [comment]
It is usually caused by an error in TFLite compilation. Please enter the tf source folder, recompile the library, and see what happened. And do you use the provided link to download the tf source codes? Currently our prototype tool do not be tested by other version of tf source codes.

**Comment by zhoumingyi** [comment]
> 

Oh, I got the reason. This is because we currently trying to support uint8 models, but I forget to test the code in float models before I make the change. it seems some codes that support the obfuscating of the quantized model will make the float model not compatible with the library. You can modify the bash file (build_obf.sh) in the project directory as follows:

```
python obfuscation.py --model_name=fruit --extra_layer=30 --shortcut=30
# ----------------------------------------------
# uncomment the following lines if you want to test the uint8 model (but we currently only support limited ops for uint8 model)
# flatc -t schema.fbs -- obf_model.tflite
# python modify_tflite.py
# flatc -b ./schema.fbs obf_model.json
# ----------------------------------------------
pip uninstall -y tensorflow
pip install /tmp/tensorflow_pkg/tensorflow-2.9.1-cp38-cp38-linux_x86_64.whl
python test_model.py --model_name=fruit
```

If you have other problems using our prototype tool, please let me know.

**Comment by zhoumingyi** [comment]
> Data type of this model is float32 Traceback (most recent call last): File "test_model.py", line 73, in model_test(os.path.join(model_path, model_name)) File "test_model.py", line 46, in model_test interpreter.allocate_tensors() File "/root/anaconda3/envs/code275/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 513, in allocate_tensors return self._interpreter.AllocateTensors() RuntimeError: Encountered unresolved custom op: Yanjwz.

Does the latest update solve your problem?

**Comment by Q1ngS0ng** [comment]
it still doesn't work but i can successfully generate the custom op files. I think it because the custom op filename is lowercase (as yanjwz.cc) but the operation in interpreter.py is uppercase(Yanjwz).

**Comment by zhoumingyi** [comment]
If the mentioned custom op file is in the tf_output_file folder, it is not the problem, because we just use it to create the tflite model. You can check the output model obf_model.tflite using [netron](https://netron.app/), it should be uppercase. 

If the output model has been successfully created (obf_model.tflite in the project directory), you can test the following command in the TensorFlow source directory one by one:

```
bazel  build //tensorflow/tools/pip_package:build_pip_package
```
```
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```
```
python -m pip uninstall -y tensorflow
```
```
python -m pip install /tmp/tensorflow_pkg/tensorflow-2.9.1-cp39-cp39-linux_x86_64.whl
```
Most of the error cases are because building the TensorFlow python package fails (the first step). Sometimes compiling the source codes is different in different machines. That's why we recommend using docker.
